# Seleção de Amostras Aleatórias

Uma operação comum em trabalhos de auditoria é a seleção de amostras aleatórias, as quais podem ser selecionadas das seguintes maneirias:

* Amostra aleatória simples com e sem reposição   
* Amostra sistemática   
* Amostra estratificada  
* Amostra com probabilidade de seleção proporcional ao tamanho (PPT)   

No R, a seleção de amostras aleatórias simples com e sem reposição pode ser realizada com a função **`sample()`**.

## Amostra aleatória simples sem reposição

No exemplo a seguir, será selecionada uma amostra aleatória simples sem reposição de 30 elementos do conjunto de dados `rh`.

In [10]:
setwd('C:\\Users\\Marcos\\Documents\\GitHub\\Usando-R-em-Auditoria\\dados')
load('rh.RData')
str(rh)
head(rh)

'data.frame':	5000 obs. of  10 variables:
 $ Sexo            : chr  "Masculino" "Masculino" "Feminino" "Feminino" ...
 $ Estado.Civil    : chr  "Casado" "Viúvo" "Casado" "Casado" ...
 $ Anos.de.estudo  : int  14 19 18 16 15 18 18 12 14 12 ...
 $ Formação        : chr  "SEC" "SEC" "SEC" "SEC" ...
 $ Tempo.de.empresa: int  19 31 28 20 15 23 27 20 11 16 ...
 $ Unidade         : chr  "Curitiba" "São Paulo" "Rio de Janeiro" "Rio de Janeiro" ...
 $ Departamento    : chr  "Produção" "Vendas" "Financeiro" "Vendas" ...
 $ Cargo           : chr  "Assistente" "Assistente" "Assistente" "Assistente" ...
 $ Salário         : num  16.7 29.1 21.8 22.6 16.7 ...
 $ Bônus           : num  28.02 41.24 16.88 13.5 8.44 ...

  Sexo      Estado.Civil Anos.de.estudo Formação Tempo.de.empresa
1 Masculino Casado       14             SEC      19
2 Masculino Viúvo        19             SEC      31
3 Feminino  Casado       18             SEC      28
4 Feminino  Casado       16             SEC      20
5 Masculino Solteiro     15             SEC      15
6 Masculino Casado       18             SEC      23
  Unidade        Departamento Cargo      Salário Bônus
1 Curitiba       Produção     Assistente 16.67   28.02
2 São Paulo      Vendas       Assistente 29.13   41.24
3 Rio de Janeiro Financeiro   Assistente 21.80   16.88
4 Rio de Janeiro Vendas       Assistente 22.61   13.50
5 Curitiba       Vendas       Auxiliar   16.67    8.44
6 São Paulo      Pessoal      Assistente  8.34   86.88

In [5]:
set.seed(1)
linhas_sorteadas <- sample(row.names(rh), 30)
amostra <- rh[linhas_sorteadas,]
amostra

     Sexo      Estado.Civil Anos.de.estudo Formação Tempo.de.empresa
1328 Masculino Casado       13             EXA      12
1861 Masculino Casado       12             BIO       6
2864 Masculino Casado       15             HUM      18
4539 Masculino Casado       12             HUM      18
1008 Masculino Casado       13             BIO      13
4488 Masculino Casado       20             SEC      19
4718 Masculino Solteiro     16             EXA      15
3300 Feminino  Solteiro     10             SEC       5
3141 Masculino Solteiro     15             EXA      17
309  Feminino  Casado       12             NA       11
1028 Feminino  Divorciado   12             SEC      24
881  Feminino  Casado       18             HUM       9
3427 Masculino Casado       13             HUM      14
1916 Feminino  Casado       17             EXA      17
3839 Feminino  Casado       14             EXA      20
2482 Feminino  Divorciado   16             SEC      17
3577 Masculino Casado       17             SEC      27
4943 Feminino  Casado       15             SEC      11
1894 Feminino  Casado       17             SEC       4
3873 Masculino Solteiro     15             SEC       7
4655 Masculino Solteiro     17             SEC       9
1057 Feminino  Casado       15             BIO      21
3245 Feminino  Casado       16             EXA      13
625  Feminino  Solteiro     15             HUM      14
1330 Masculino Divorciado   16             SEC      11
1921 Masculino Casado       20             SEC      26
67   Feminino  Casado       16             SEC      17
1902 Feminino  Casado       16             EXA      13
4325 Masculino Casado       17             SEC       3
1692 Masculino Casado       19             EXA      21
     Unidade        Departamento Cargo      Salário Bônus
1328 São Paulo      Vendas       Assistente  9.73   33.68
1861 Curitiba       Produção     Auxiliar    8.04    6.58
2864 Florianópolis  Produção     Assistente 14.01   49.48
4539 São Paulo      Produção     Auxiliar    3.65   10.52
1008 São Paulo      Vendas       Assistente 11.79    4.24
4488 Rio de Janeiro Vendas       Gerente    30.12   48.60
4718 Curitiba       Vendas       Assistente  9.17    3.66
3300 Rio de Janeiro Produção     Auxiliar    1.60    5.14
3141 São Paulo      Vendas       Assistente  4.34    9.44
309  Rio de Janeiro Pessoal      Assistente  6.93   10.24
1028 São Paulo      Financeiro   Auxiliar    2.45    2.54
881  São Paulo      Vendas       Assistente 14.76   18.78
3427 Curitiba       Financeiro   Auxiliar    5.55    4.90
1916 São Paulo      Vendas       Assistente  6.75   20.60
3839 Rio de Janeiro Vendas       Assistente  6.67   29.20
2482 São Paulo      Financeiro   Assistente  8.14   17.30
3577 Rio de Janeiro Vendas       Assistente 20.05   41.24
4943 Rio de Janeiro Produção     Auxiliar    3.10    6.78
1894 São Paulo      Vendas       Assistente 13.71   16.28
3873 São Paulo      Pessoal      Auxiliar    5.63    7.30
4655 São Paulo      Vendas       Assistente  5.48   20.14
1057 Curitiba       Vendas       Assistente 12.45    8.80
3245 São Paulo      Produção     Assistente  5.33    9.18
625  Rio de Janeiro Financeiro   Auxiliar    2.49   25.18
1330 Rio de Janeiro Produção     Assistente  7.56   11.86
1921 Rio de Janeiro Vendas       Assistente 42.18   61.26
67   Rio de Janeiro Vendas       Assistente  8.04   48.18
1902 São Paulo      Vendas       Auxiliar   16.84   27.72
4325 Rio de Janeiro Vendas       Gerente    23.87   77.10
1692 São Paulo      Pessoal      Assistente 17.34   12.18

A função `set.seed()` serve para se definir uma semente para geração dos números aleatórios. Isto garante que se outra pessoa utilizar a mesma semente e sortear uma amostra aleatória semples sem reposição, obterá a mesma amostra mostrada acima. No caso do exemplo foi utilizado o valor 1 como semente mas poderia ser qualquer outro valor.

A seleção de amostras com reposição, de pouco interesse em auditoria, é feita utilizando-se o argumento `replace = TRUE` na função `sample()`.

## Seleção de amostras estratificadas

Além da seleção de amostras aleatórias simples, pode-se sortear amostras estratificadas e amostras com probabilidade de seleção proporcional ao tamanho.

A seleção de amostras estratificadas consiste em dividir o conjunto de dados em estratos e, dentro de cada estrato, sortear amostras aleatórias simples.

A quantidade de itens a serem sorteados cada estrato pode dar-se com igual quantidade de itens sendo sorteada em cada estrato ou quantidades de itens sorteados em cada estrato proporcionais ao tamanho do estrado na população total de itens. Veremos como implementar estas duas possibilidades.

### Iguais quantidades de itens em cada estrato

Supondo que desejamos sortear amostras de pessoas do sexo masculino e feminino, ambas com 15 elementos, pode-se proceder da seguinte forma:

In [6]:
set.seed(2)
rh_lista <- split(rh, f=rh$Sexo)
amostra <- lapply(rh_lista,
                  function(x)x[sample(row.names(x), size=15),])
amostra <- do.call(rbind, amostra)
row.names(amostra) <- 1:nrow(amostra)
amostra

   Sexo      Estado.Civil Anos.de.estudo Formação Tempo.de.empresa
1  Feminino  Viúvo        14             EXA       0
2  Feminino  Divorciado   11             SEC      11
3  Feminino  Casado       10             SEC       3
4  Feminino  Casado       15             BIO      28
5  Feminino  Casado       14             SEC      15
6  Feminino  Viúvo         8             HUM       0
7  Feminino  Solteiro     16             SEC       9
8  Feminino  Casado       13             HUM       3
9  Feminino  Casado       10             HUM       3
10 Feminino  Casado       12             HUM       3
11 Feminino  Casado       15             SEC       0
12 Feminino  Solteiro     15             SEC      20
13 Feminino  Casado       12             SEC      19
14 Feminino  Casado       15             SEC      21
15 Feminino  Viúvo         8             EXA       0
16 Masculino Viúvo        15             SEC       5
17 Masculino Divorciado   13             EXA       0
18 Masculino Viúvo        14             EXA       7
19 Masculino Casado       14             SEC      18
20 Masculino Casado       12             SEC       8
21 Masculino Viúvo        16             SEC       8
22 Masculino Casado       22             SEC       1
23 Masculino Viúvo        15             SEC      10
24 Masculino Casado       15             SEC       5
25 Masculino Casado       20             SEC      25
26 Masculino Casado       17             SEC      24
27 Masculino Casado       13             HUM       9
28 Masculino Casado       15             EXA       7
29 Masculino Casado       13             BIO       7
30 Masculino Casado       17             SEC      20
   Unidade        Departamento Cargo      Salário Bônus
1  Florianópolis  Produção     Auxiliar    2.985   3.76
2  São Paulo      Produção     Auxiliar    2.880   2.20
3  Florianópolis  Produção     Auxiliar    1.200   5.48
4  Rio de Janeiro Vendas       Assistente  5.860   7.96
5  Curitiba       Produção     Assistente 10.300  22.82
6  Florianópolis  Produção     Auxiliar    1.080   2.52
7  Rio de Janeiro Vendas       Auxiliar    4.220  11.10
8  Curitiba       Produção     Auxiliar    3.050   7.62
9  Florianópolis  Produção     Auxiliar    1.770   2.92
10 Rio de Janeiro Pessoal      Auxiliar    9.390  16.28
11 Florianópolis  Vendas       Assistente  7.940   6.10
12 Curitiba       Financeiro   Assistente  7.010  21.56
13 Curitiba       Produção     Auxiliar    7.660   3.42
14 Florianópolis  Financeiro   Auxiliar    7.470   9.30
15 Rio de Janeiro Produção     Auxiliar    1.160   2.50
16 Rio de Janeiro Financeiro   Assistente  5.930   9.04
17 Curitiba       Financeiro   Auxiliar    1.710   6.28
18 Curitiba       Produção     Auxiliar    2.530   6.00
19 Rio de Janeiro Vendas       Assistente 24.520  19.68
20 Rio de Janeiro Produção     Assistente 12.590  26.28
21 São Paulo      Produção     Assistente  4.920  11.86
22 Curitiba       Vendas       Assistente 17.690  45.64
23 Rio de Janeiro Vendas       Assistente 11.530  47.74
24 São Paulo      Vendas       Auxiliar    4.850  16.48
25 Rio de Janeiro Vendas       Gerente    66.540  68.06
26 Rio de Janeiro Vendas       Assistente 34.570  41.62
27 Curitiba       Produção     Auxiliar    4.650   2.70
28 São Paulo      Financeiro   Auxiliar    3.920   4.98
29 Rio de Janeiro Produção     Assistente  6.420   9.70
30 Rio de Janeiro Vendas       Assistente 18.040  61.76

###  Alocação proporcional

No exemplo a seguir os estratos são definidos pelos valores da variável `Departamento` do conjunto de dados. O objetivo é sortear uma quantidade de itens em cada estrato dada por uma fração do tamanho da amostra igual à fração que cada `Departamento` representa no total de itens do conjunto de dados. Assim, por exemplo, se a quantidade de funcionários que trabalham no departamento financeiro representam 14% da quantidade de registros no conjunto de dados, serão sorteados neste estrato 14% do tamanho da amostra.

O código a seguir ilustra como realizar este sorteio:

In [18]:
# tamanho da população
N <- nrow(rh) 
# proporção de registros de cada Departamento na população
proporcao <- prop.table(table(rh$Departamento)) 
# tamanho da amostra
n <- 50  
# tamanho em cada estrato - proporcional
sample_sizes <- as.vector(round(proporcao * n, 0)) 

rh_lista <- split(rh, f=rh$Departamento)
sorteia_amostra <- function(x, n) x[runif(n, 1, nrow(x)),]

set.seed(2)
amostra <- Map(sorteia_amostra, rh_lista, sample_sizes)
amostra <- do.call(rbind, amostra)
row.names(amostra) <- 1:nrow(amostra)
amostra

   Sexo      Estado.Civil Anos.de.estudo Formação Tempo.de.empresa
1  Masculino Casado       15             BIO       1
2  Masculino Casado       13             SEC      17
3  Masculino Divorciado   14             SEC      10
4  Masculino Casado       19             HUM      27
5  Feminino  Casado       18             SEC      29
6  Feminino  Casado       18             SEC      29
7  Masculino Casado       11             SEC       9
8  Masculino Casado       11             SEC      22
9  Masculino Viúvo        12             SEC      12
10 Feminino  Solteiro     13             EXA       9
11 Feminino  Casado       13             HUM      15
12 Feminino  Casado       11             EXA       0
13 Masculino Casado       13             SEC      10
14 Feminino  Casado       14             EXA       5
15 Masculino Casado       12             SEC      10
16 Masculino Casado       18             SEC      26
17 Masculino Casado       20             EXA      10
18 Feminino  Casado       13             EXA      10
19 Feminino  Casado       13             BIO      22
20 Feminino  Viúvo        13             EXA       6
21 Feminino  Solteiro     10             BIO       8
22 Masculino Solteiro     12             EXA       8
23 Feminino  Divorciado   14             EXA      12
24 Masculino Casado       14             BIO       7
25 Masculino Solteiro     12             SEC       9
26 Masculino Casado       14             SEC       1
27 Masculino Viúvo        17             BIO      32
28 Masculino Casado       18             SEC      32
29 Feminino  Casado       16             SEC       5
30 Feminino  Viúvo        15             HUM      13
31 Feminino  Casado       16             SEC      17
32 Masculino Casado       14             HUM      23
33 Masculino Solteiro     20             SEC      19
34 Masculino Casado       19             HUM      26
35 Masculino Solteiro     17             EXA      11
36 Masculino Casado       19             HUM      14
37 Feminino  Casado       19             EXA      32
38 Masculino Viúvo        18             SEC      23
39 Feminino  Casado       15             HUM      24
40 Masculino Viúvo        16             SEC       4
41 Masculino Solteiro     20             HUM      19
42 Feminino  Casado       17             SEC      29
43 Masculino Viúvo        15             HUM      37
44 Masculino Casado       20             SEC      11
45 Masculino Divorciado   20             SEC      14
46 Masculino Divorciado   16             HUM      19
47 Feminino  Casado       13             SEC       9
48 Masculino Casado       19             EXA      20
49 Feminino  Casado       15             SEC      20
50 Masculino Casado       11             SEC      20
   Unidade        Departamento Cargo      Salário Bônus
1  Rio de Janeiro Financeiro   Assistente  7.28    32.02
2  Florianópolis  Financeiro   Assistente 10.91    60.74
3  Rio de Janeiro Financeiro   Assistente  2.74     3.98
4  Rio de Janeiro Financeiro   Assistente 22.41    52.14
5  Curitiba       Financeiro   Gerente    18.57   119.19
6  Curitiba       Financeiro   Gerente    18.57   119.19
7  Curitiba       Financeiro   Auxiliar    2.53    13.00
8  Curitiba       Pessoal      Auxiliar   15.69    45.22
9  São Paulo      Pessoal      Auxiliar    1.96     3.22
10 Florianópolis  Pessoal      Auxiliar    1.71     2.24
11 Curitiba       Pessoal      Auxiliar    3.19    26.56
12 Florianópolis  Pessoal      Auxiliar    1.20     2.24
13 Curitiba       Pessoal      Assistente  8.44    13.50
14 Florianópolis  Produção     Auxiliar    1.49    10.10
15 Curitiba       Produção     Assistente 12.86     9.30
16 São Paulo      Produção     Assistente 28.41    31.70
17 Curitiba       Produção     Auxiliar    7.28    11.84
18 São Paulo      Produção     Auxiliar    2.27     2.54
19 Curitiba       Produção     Assistente  7.85     4.24
20 Curitiba       Produção     Auxiliar    1.49     6.68
21 Curitiba       Produção     Auxiliar    1.60     2.36
22 Florianópolis  Produção     Auxiliar    1.63     2.46
23 Rio de Janeiro Produção     Auxiliar    2.16    18.14
24 Curitiba       Produção     Assistente  5.41    23.06
25 Florianópolis  Produção     Auxiliar    4.52    14.76
26 Florianópolis  Produção     Assistente  6.09    24.36
27 Rio de Janeiro Vendas       Assistente  5.86    16.28
28 Rio de Janeiro Vendas       Assistente  6.67    19.00
29 Rio de Janeiro Vendas       Assistente 17.52    30.12
30 Florianópolis  Vendas       Assistente  1.16    14.76
31 Rio de Janeiro Vendas       Assistente  8.04    48.18
32 Rio de Janeiro Vendas       Auxiliar   12.45     2.68
33 Curitiba       Vendas       Assistente 11.03    22.30
34 Rio de Janeiro Vendas       Assistente 20.05    92.06
35 Rio de Janeiro Vendas       Auxiliar    7.38    18.78
36 Rio de Janeiro Vendas       Assistente 31.13    28.60
37 Rio de Janeiro Vendas       Assistente 16.01    27.72
38 Rio de Janeiro Vendas       Assistente 18.57    41.24
39 Rio de Janeiro Vendas       Assistente 14.45     7.52
40 Rio de Janeiro Vendas       Assistente  9.96    10.96
41 Rio de Janeiro Vendas       Assistente 13.14    47.74
42 Rio de Janeiro Vendas       Assistente 22.41   108.06
43 Rio de Janeiro Vendas       Assistente 12.86    19.00
44 São Paulo      Vendas       Assistente 15.53    65.92
45 Rio de Janeiro Vendas       Assistente 13.00    41.24
46 Rio de Janeiro Vendas       Assistente 16.84    20.60
47 Rio de Janeiro Vendas       Assistente  7.01    38.60
48 Rio de Janeiro Vendas       Assistente 14.15    57.78
49 Rio de Janeiro Vendas       Assistente  7.47     9.18
50 São Paulo      Vendas       Auxiliar    4.98     6.10

In [20]:
round(proporcao, 2)
prop.table(table(amostra$Departamento))

Financeiro    Pessoal   Produção     Vendas
      0.14       0.12       0.27       0.48

Financeiro    Pessoal   Produção     Vendas
      0.14       0.12       0.26       0.48

Os comandos acima mostram que as proporções de registros na população e na amostra são as mesmas.

## Probabilidade de seleção proporcional ao tamanho

A seleção de amostras com probabilidade de seleção proporcional ao tamanho pode ser obtida passando-se ao argumento `prob=` da função `sample()` um vetor com as probalidades de seleção de cada elemento. Usualmente este vetor é obtido calculando, para alguma variável de interesse, qual a participação de cada registro na soma dos valores desta variável.

Exemplo. Se a variável de interesse é o `Salário` então o vetor de probabilidades é obtido da seguinte forma:

In [14]:
rh$Salário <- ifelse(is.na(rh$Salário), 0, rh$Salário)
peso <- rh$Salário / sum(rh$Salário, na.rm=TRUE)

A seleção de uma amostra de tamanho 10 com probabilidade de seleção proporcional ao tamanho pode ser feita da seguinte forma:

In [15]:
set.seed(130)
linhas_sorteadas <- sample(row.names(rh), size=10, prob=peso)
amostra_ppt <- rh[linhas_sorteadas,]
amostra_ppt

     Sexo      Estado.Civil Anos.de.estudo Formação Tempo.de.empresa
4099 Feminino  Casado       15             SEC      25
880  Feminino  Casado       19             SEC      34
3104 Masculino Casado       18             SEC      24
3441 Masculino Casado       17             SEC      26
868  Masculino Casado       17             EXA      22
4141 Masculino Casado       15             BIO       2
47   Masculino Viúvo        21             SEC      25
2031 Masculino Casado       18             SEC      30
2055 Masculino Casado       19             HUM      30
3830 Feminino  Casado       16             SEC      22
     Unidade        Departamento Cargo      Salário Bônus
4099 São Paulo      Financeiro   Auxiliar    4.10    21.08
880  Rio de Janeiro Vendas       Assistente 36.52    22.06
3104 Rio de Janeiro Pessoal      Gerente    32.69    53.06
3441 Rio de Janeiro Vendas       Assistente 34.85    85.62
868  São Paulo      Financeiro   Assistente 18.75   125.70
4141 Rio de Janeiro Financeiro   Auxiliar    6.33    16.08
47   Rio de Janeiro Vendas       Gerente    48.38    71.36
2031 Rio de Janeiro Vendas       Assistente 34.03    39.34
2055 Rio de Janeiro Vendas       Assistente 45.05    19.22
3830 Rio de Janeiro Vendas       Assistente 13.71    10.38

Com este procedimento de amostragem, os registros com maior valor de salário terão maior probabilidade de seleção.

**Marcos F Silva**